### ISSUE TITLE
D2 Fest Campus 문의사항용 이슈

### ISSUE THREAD

**Issue by OsoriAndOmori** [NaLDo627/ReplayUIModule#30]
안녕하세요. 네이버 스포츠에서 일하고 있는 김기훈 입니다 ^^;
제가 생각한 말도 안되는 어플리케이션 구현해주시느라 매우 고생많으셨습니다 ㅎㅎ 
게임을 좋아하시는 분들이라면 그나마 즐겁게 작업하지 않으셨을까 생각해봅니다. 
저도 고민하는 내내 즐거웠습니다.

행사 주최측에서 받은 가이드론 8월 14일까지 평가 제출 하라고 합니다. 
그래서 다음주 평일중으로 면밀하게 살펴볼 예정인데요.
고치고 싶은 부분이 있다면 중간중간 커밋 정도는 하셔도 될 것 같습니다. 
(이전 히스토리 바꾸는 force push 는 지양)

자주 들어올테니 저에게 궁금하신건 여기 이슈에 적어주셔도되고, 제 메일로 문의주셔도됩니다. 
메일을 잘보는 편이 아니라 사내, 개인메일을 동시에 보내주시면 인지를 좀 금방해서 보다 빨리 답변드릴수있습니다.
`skywhite15@korea.ac.kr` `skywhite15.kkh@navercorp.com` 

저 역시 테스트 도중에  문의사항 생기는 것은 요 이슈에 질문 하도록 하겠습니다.

끝으로 어떠한 결과가 나오더라도, 개발적인 이야기나 네이버 실제 서비스, 현업이야기 등등 
궁금한건 편하게 나눌 수 있는 좋은 관계가 되었으면 좋겠습니다~ 
감사합니다.

**Comment by OsoriAndOmori** [comment]
@NaLDo627 @kuotient46 @huthealth 
확인차 문의드립니다~
코드는 다 띄워보고 확인을 했습니다.

만약 새로운 게임이 추가 된다면 위 프로젝트에서 할 일을 적어보았는데요 맞는지 확인 한번 부탁드립니다~
## back
- Api 컨트롤러에 게임추가, 게임사 Api 호출하고, 화면단에서 쓸 컨버팅 하는 비즈니스 로직
- 리턴할 모델에서 players 데이터만 화면단 로직에 맞게 Response 모델링

## front
- router 추가,
- 화면구성 컴포넌트 (이벤트, 속도)
- Telemetry.js Timeline.js 같은 화면 반영, 

제가 프로젝트에서 받은 느낌은 롤 리플레이랑, 배그 리플레이를
back, front 끼리 합쳐 놓은 느낌을 받았는데요, 혹시 어떻게 생각하시는지 궁금합니다.
전체적인 UI 완성도는 매우 높아보이는데, 
모듈화에 관한 프로젝트 방향도 어느정도 파악을 하기 위해서입니다 ㅎㅎ
UAZ 타고 가는건 엄청 웃었네요 ㅎㅎ

<img width="107" alt="스크린샷 2019-08-06 오전 11 43 22" src="https://user-images.githubusercontent.com/22016317/62507522-b0ca2900-b83f-11e9-96b2-fcbeaed3b06a.png">

**Comment by NaRDo627** [comment]
@OsoriAndOmori 
안녕하세요. 
넵 만일 새로운 게임이 추가가 된다면, 적어주신 내용들의 작업이 기본적으로 이루어지게 될 것입니다.
적어주신 내용 외 추가로 할 일이 있다면 다음과 같습니다.

## Back
- 리턴할 모델에 players에 매치에 참여한 플레이어 정보, match에는 매치 전반적인 정보(플레이시간, 경기 결과 등), rawReplayData에 실제 인게임 리플레이 데이터(게임사 API에서 받아온 telemetry, timeline등의 데이터) 등을 담아 리턴

## Front
- 추가된 게임의 rawReplayData에 대한 파서 추가 (ex. Telemetry.parser.js)
- router추가 후, 해당 page에서 Replay.worker.js 및 파서 호출하는 부분 추가 (fetch를 사용해 back으로부터 데이터를 가져옴)
- Replay.worker.js 에서 추가된 게임에 대한 Back API 호출 추가

컴포넌트에 대한 모듈화는 공용으로 사용할 수 있는 부분은 가급적 공용으로 묶고, 롤, 배그 따로 사용하는 부분은 컴포넌트를 분리하였습니다. 
롤 리플레이와 배그 리플레이를 back, front 끼리 합쳐 놓은 느낌을 받으셨다고 하는데, 말씀하시는 의미를 잘 모르겠습니다. 혹시 back, front 내에서 배그, 롤 에 대한 소스코드가 합쳐있는 듯한 느낌을 말씀하시는 거라면, 공용으로 사용할 수 있는 소스코드(TimeTracker.js 등)는 상위 디렉토리, 배그와 롤 전용 소스코드는 그 하위 디렉토리에 넣었기 때문입니다. 저희가 리액트 자체는 처음이라 어떤 구조가 좋을지 몰라, 앞서 설명드린 방식대로 구성하였습니다.
촉박한 시간 내에 구현에만 집중하다보니, 모듈화에 대한 생각이 부족했던 것은 사실인 것 같습니다. 혹시 따로 생각하고 계신 모듈화 방법이 있으신가요??

**Comment by OsoriAndOmori** [comment]
네~ 모두 다 몇 일에 걸친 정성스러운 프로젝트라 저는 생각하는 편이라
요런건 확실하게 짚고 넘어가는게 좋을 것 같아 말씀드립니다.

[D2 공홈](http://d2campusfest.kr/7th/) , [FAQ](https://github.com/D2CampusFest/7th/wiki/5.-%EA%B2%8C%EC%9E%84-%EB%AF%B8%EB%8B%88%EB%A7%B5-%EB%A6%AC%ED%94%8C%EB%A0%88%EC%9D%B4(replay)-%EB%AA%A8%EB%93%88)

## #문제에서 의도한 바
프로젝트에 대한 설명으로

`게임사로부터 제공받은 다양한 형태의 게임 api를 일정한 포맷으로 컨버팅만 하고 submit을 해주면, Replay가 가능한 미니맵을 내려주는 web application 구현.
이 모듈을 사용하는 사용자는, 데이터를 정해진 형태로 컨버팅해서 제출하는 부분만 구현하면 됨`

이라고 해두었습니다. FAQ 보면 조금 자세한 그림이 그려져있는데요.
본래 제가 의도한 프로젝트는 **"롤 리플레이, 배그 리플레이를 재생하는걸 만들어라!"** 가 아니고 
극단적이긴 하지만 대충 아래 그림과 같습니다 ~

파란색 글씨를 좀 주목해서,, LoL, 배그를 같은 데이터 포맷으로 컨버팅을 한다면 굳이 게임별로 front 코드를 나누지 않아도 될 것 같다는 생각이 드실거라 생각합니다

오버워치 Api 가 드디어 나왔고 만약 요것도 리플레이에 추가를 할 때? 
asset을 제외한 front는 사실 손을 안대도 되는 거죠. 
이런 모듈은 각 게임 별로 다른 아주 마이크로한 기획까지 반영하긴 쉽지 않겠지만, 
오버워치 Api 가 나온다고 가정했을 때, `게임사 api 끌어다가 정해진 포맷으로 컨버팅 후 제출` 만하면 
적절한 리플레이가 만들어질것이라고 생각했습니다.

<img width="737" alt="스크린샷 2019-08-06 오후 1 33 29" src="https://user-images.githubusercontent.com/22016317/62511864-8f256d80-b850-11e9-9297-fe082668b6b8.png">

## #만들어주신 프로젝트 구성도
그런 의미에서 만들어주신 프로젝트는 아래 그림과 유사해보입니다. 요렇기에 제가 다른게임 
back, front 를 합쳐놓은 느낌이라고 말씀드린거구용.

![KakaoTalk_Photo_2019-08-06-13-44-08](https://user-images.githubusercontent.com/22016317/62511948-e9263300-b850-11e9-98cc-4b47b2e9761d.jpeg)

그렇다고 아예 방향이 다르니 실격이다 이런건 전혀 아닙니다. 
결국 이 정도 작업해놨으면 조금만 수정하면 최종 결과물에 다다를 수 있고, 
UI 적인 완성도도 모두 평가에 반영이 되고 있으니깐요.

주저리 주저리 썼는데 이해가 되셨을지 모르겠습니다.
혹시나 잘 이해 안되셨으면 말씀해주세요 ^^;

**Comment by NaRDo627** [comment]
@OsoriAndOmori 
정성껏 답변주셔서 정말 감사합니다!
넵 사실 저 FAQ는 제가 메일로 물어본 내용입니다 ㅎㅎ; 다만 데이터 컨버팅 부분이 저희 백엔드에서 이루어지는 것으로 이해를 해버려서, 이와 같은 결과물이 나오게 된 것입니다.
적어주신 내용이 아주 잘 이해가 되어서, 저희가 작업한 방향이 어긋났다는 것을 깨닫는데는 어렵지 않았습니다. 가능한 한 말씀주신대로 리팩토링 작업을 진행해보도록 하겠습니다.

**Comment by NaRDo627** [comment]
@OsoriAndOmori 
문의 드립니다.
개발 가정은 데이터 컨버팅을 사용자에게 전적으로 부담하는 것으로 되어있는데, 컨버팅 일부는 저희 백엔드에서 담당하는 식으로 변경하는 것은 어떨까요?
예를 들어 players, match 등의 정보는 사용자가 저희가 지정한 방식으로 컨버팅 하여 보내야 하지만, rawReplayData같은 경우에는 각 API 사에서 보낸 raw 데이터 (telemetry와 timeline)를 그대로 보내도록하여 저희 백엔드에 보내면, 백엔드에서 그 데이터를 파싱하여 프론트로 replay 재생 데이터를 보내는 것으로요. 즉 기존 경기 파서가 front 에서 back으로 이동하게 되는 구조입니다.
이 경우엔 새로운 경기를 추가할 때 저희가 직접 파서를 다시 만들어야 한다는 부담은 있지만, 사용자 입장에서는 사용하기가 더 수월해질 것입니다. front 컴포넌트 변경도 최소화 시킬 수 있구요.

**Comment by OsoriAndOmori** [comment]
아 넵넵 결국 핵심은 게임별루 백엔드 데이터 가공이 거의 비슷한 확장가능한 포맷으로 가야하는것 같습니다.
Front가 리플레이 모듈이 될 것이라고 생각합니다.
(프로젝트 체크아웃 받아서 사용자가 백엔드에 parser 추가해서 만드는게 데이터 컨버팅과정이겠죠)

발로 묘사하긴했지만... 
제가 개발을 했다면 아마 겜별로 하나씩 구분해서 요런형태로 가지않았을까 싶습니다.

<img width="755" alt="스크린샷 2019-08-06 오후 3 19 26" src="https://user-images.githubusercontent.com/22016317/62515560-a0c14200-b85d-11e9-9f00-43e86f3457d5.png">

---------------------------

번외로 이제 저는 평가를 하는 입장에서 ㅎㅎ 제출일 이후에 수정된걸 `감안`을 할 수는 있으나,
다른 지원자들과의 형평성으로 인하여 큰 변동폭의 평가 변경을 하긴 어렵습니다. 
(혹시나하여 말씀드리니 요정도는 이해해주시리라 생각합니다)

개발적인 질문은 언제나 환영하니 말씀해주세요~

**Comment by NaRDo627** [comment]
@OsoriAndOmori 
넵, 확인차 다시 질문하겠습니다.

## 현재
현재 제출한 저희의 시나리오는 이렇습니다.
![현재](https://user-images.githubusercontent.com/36787678/62522673-24365f80-b86d-11e9-860a-a8cd7cd07dd1.PNG)
1. 사용자가 URL 파라미터로 platform, matchId 등을 Front로 보냅니다.
2. Front는 Back으로 전달받은 URL 파라미터를 API 호출 주소에 붙여서 보냅니다. (ex. /api/lol/{platform}/{matchId})
3. Back에서는 게임사 API로 요청을 보내고, RAW 데이터를 받아, 위의 Data 형식대로 짜넣어, 리플레이 데이터에 대해 파싱은 하지 않고 Front로 보냅니다.
4. Front에서는 Back에서 보낸 데이터를 파싱하여 ReplayUI를 만들어 사용자에게 보여줍니다.

제가 잘못 이해했을지도 모르지만, Back에서 데이터셋에 맞춰서 보내준다는 점은 개발자님 생각과 비슷한 것 같습니다. 하지만 현재 상태의 Front는 Pubg, Lol의 리플레이"만"을 보여준다는 성격이 강하며, 만약 이 구조에서 크게 벗어나지 않고 개선을 한다면, Front의 컴포넌트를 모든 게임에서 공통으로 사용하도록 변경하는 작업을 할 것 같습니다. 또한 rawReplayData를 replayData(혹은 replayFrame 등)로 이름을 변경하고, Backend에서 게임사로부터 받은 Raw Data를 파싱하여 Array Object 형태로 Front에서 받아 재생만 하는 것으로 변경할 것 같습니다.(방안 1)

## 구조 리팩토링 아이디어
제가 말씀드리고자 했던 리팩토링 아이디어는 다음과 같습니다.
![개선](https://user-images.githubusercontent.com/36787678/62523651-3913f280-b86f-11e9-8fe2-98f6857303b1.PNG)
1. 사용자는 직접 게임사 API로부터 데이터를 가져온 후, 데이터 컨버팅을 하여 저희가 정한 Data형식에 맞게 만듭니다. (rawReplayData 에는 파싱되지 않은 raw telemetry, timeline 등이 들어있습니다.)
2. Front에서는 파일 업로드나 Textbox 등으로 JSON Data를 입력받은 후, ajax 등을 사용하여 사용자의 데이터를 그대로 받아 Back에 전달해 줍니다. (혹은 POST요청으로 파일 업로드나 Textbox를 생략할 수 있습니다.)
3. Back에서는 받은 Data를 파싱하여 ReplayFrames(가제) 객체를 만들어 Front에 리턴합니다. 이때 ReplayFrames에는 플레이어 위치, 킬 상태 등의 시간별 매치 데이터가 배열 객체로 들어있습니다.
4. Front는 ReplayFrames를 읽어 들여 ReplayUI를 보여주기만 하면 됩니다.

이 아이디어대로 리팩토링을 진행한다면 원래의 목적에 보다 더 맞게 바꿀 수 있으며, 새로운 게임 추가시 작업도 에셋과 파서 추가 외에는 별로 없어 보입니다.(방안 2)

방안 1은 현실적, 방안 2는 이상적 리팩토링으로 생각되어 집니다. 개인적으로는 방안 2로 진행해 보고 싶은데, 개발자님 생각은 어떤지 궁금합니다.

## 번외로 말씀주신 부분에 대하여
평가 점수가 변할 수 없다는 것은 당연히 알고있습니다. 공개된 내용으로는 심사 기준 커밋이 7월 31일까지인 것으로 알고 있고, 그 이후에 커밋된 내용이 평가에 반영된다면 공정성에 해가 될 여지가 있다는 것을 알고 있습니다. 그러니 신경쓰실 필요 없습니다^^. 그럼에도 불구하고 위처럼 아이디어를 낸 것은, 개발자로서 고객의 요구사항을 최대한 충족 시키고자 하는 마음이 있기 때문입니다. 또한 개인적인 공부에도 큰 도움이 되겠지요 ㅎㅎ

**Comment by OsoriAndOmori** [comment]
아 네 정독해서 모두 이해했습니다.
방안 2가 저는 개인적으로 마음에 드나 역시 수술하는데 큰 작업량이 들 것 같네요 ㅎㅎ
하지만 나중에 현업가셔도 결국 [확장성 있는 모듈/어플리케이션] 을 위한 작업을 많이 하게 되고, 
그렇게 만든 사람이 우대 받는 것 같습니다. 
천천히 기간을 가지고 설계 하시면서 동료들과 나눠서 해보시는걸 추천합니다. 
(게임사에서도 좋아할 것 같습니다)

작업하신 내용은 이미 충분히 가치 있어보입니다.
노력해주셔서 감사하고, 언제든 궁금한것 / 리뷰 같은것도 말씀해주세요~

**Comment by NaRDo627** [comment]
@OsoriAndOmori 
개발 문의 드립니다.
#33 이슈대로 FrontEnd, 즉 리액트에서 데이터 입력 받는 부분을 Refactoring 하고자 하는데, 입력을 Textbox로 구현하여 backend와 통신하게 만드는 것은 쉽지만, POST방식 등으로 들어온 데이터를 바로 넘기는 방법을 모르겠습니다. 어찌보면 당연한 말일지도 모르지만, react-router에서는 GET 외에는 받지 못한다고 합니다. 
한가지 아이디어는 있는데, POST 요청은 BackEnd, 즉 스프링 부트 쪽으로 바로 보낸 후, 스프링 부트에서는 데이터 파싱 후 **그 데이터를 set cookie 기능을 이용해 쿠키에다가 저장**후, FrontEnd로 리다이렉트 하게끔 하여 읽게 하는 방법이 떠올랐습니다(FrontEnd에서 쿠키를 검사하여, 만약 데이터가 있으면 그 데이터를 가지고 auto submit을 하게 한다던지 등).
이 방법대로 구현은 할 수 있을 것 같지만, 너무 주먹구구식이고, backend 주소를 사용자에게 알려줘야 한다던가, 혹여나 cookie를 지원하지 않는 환경이라면 사용하지 못하는 등 제약이 많아서 사용하긴 힘들 것 같습니다.
혹시 FrontEnd에서 POST 요청 등으로 data를 직접 받아 BackEnd로 넘길 수 있는 방법이 있을까요??

**Comment by OsoriAndOmori** [comment]
답변이 매우 엄청나게 늦었네요! 
메일을 확인하는 편인데, 긴 휴가였어서 저도 모르게 읽음처리 했나봅니다.

일단 쿠키를 이용해 데이터 주고받는것은 말씀하신대로 완전 주먹구구같습니다 ㅎㅎ
토이 프로젝트 할 때엔 어떻게든 되기만하면 좋으니, 그렇게 하더라도 오픈소스 타이틀을 걸었으면 규약에 맞추는 것이 중요해보입니다 ㅎㅎ

사실 전 react 로 작업을 해본적은 없습니다. 
여러분들이 만들어 주신 것 디버깅 정도만 가능한 수준이라 react-router 에 대해 잘 알지는 못하는데요,
제가 알아보다 모르겠겠으면 실제 잘하는 친구에게 문의해드릴 수 있을 것 같습니다.

요 아래 중에 어디인지 알려주시면 좋을 것 같네요~
<img width="625" alt="스크린샷 2019-08-19 오후 2 44 06" src="https://user-images.githubusercontent.com/22016317/63241791-e800f700-c28f-11e9-9786-b728d07ca853.png">

**Comment by NaRDo627** [comment]
@OsoriAndOmori 
넵 제가 말씀드린 부분은 Actor로부터 Front, Front에서 Back으로 가는 Data부분입니다. 만약 Actor가 Front쪽으로 Data를 바디에 담아 POST 요청을 보내면, Front가 바디 부분을 읽은 후 Back으로 전달하게끔 하고 싶습니다. 이와 같은 방법이 잘 안된다면, 요청을 처음부터 Back에다가 해야 하는지도 의문입니다.
![개선_2](https://user-images.githubusercontent.com/36787678/63250645-0faf8980-c2a7-11e9-936d-a287b5f95193.png)

**Comment by OsoriAndOmori** [comment]
우선 파란색으로 한번에 가는 것은 이상한 것 같습니다. front에서 요청을하고 리플레이 html 을 받아야하지 않나요?

이젠 평가가 끝나서 제출을 저도 했기에 좀 편하게 말씀 드릴 수 있을 것 같은데요, 
다른 팀의 경우엔 ~ 
1번 부분을 http request 로 하지 않고, textArea를 파놓고 입력/복붙 하라고하거나,
file load 를 시킨곳도 있습니다. 
그리고 버튼을 누르면 back end 로 요청을 하거나 합니다.
(요렇게 하면 event handler 같은것을 통해서 ajax 로 어렵지 않을 것 같네요.)

어떤 형태로 하고자 하시는지 알긴알겠는데 제가 react 쪽으로 부족한지라 ㅎㅎ 
다른분들께 한번 여쭤보고 답변드리겠습니다.

**Comment by NaRDo627** [comment]
@OsoriAndOmori 
넵 말씀주신 부분처럼, 1차적으로는 TextArea를 파놓고 받아서 ajax나 fetch등으로 backend와 통신하게 하는 것으로 하려 했습니다. 거기서 추가로 제 3자 프로그램에서 저희 모듈을 좀 더 쓰기 편하게 쓰기 위해서라면 말씀드린 방법처럼 POST로 요청받게끔 하여 리플레이를 작동시키는 것이 어떨까 하여, 아이디어를 구해본 것이었습니다 ㅎㅎ
우선은 TextArea로 받는 식으로 리팩토링을 해야겠네요. 함께 고민해주셔서 감사합니다!

**Comment by OsoriAndOmori** [comment]
수고 너무 많이 하셨구 노력 많이 하셨는데 아쉽습니당 ~ ㅠㅠ 

나중에라도 팀원 분들 네이버 지원하실 일, 혹시 있으면 말씀하세요 ~ 
임직원 추천이 가능했던것 같은데 그런것도 한번 알아봐 드리겠습니다 ㅎㅎ
이슈는 마무리하겠습니다 ~

**Comment by NaRDo627** [comment]
@OsoriAndOmori 
비록 수상은 못했지만, 프로젝트를 하면서 많은 것을 배우게 되었습니다. 수상 여부를 떠나 의미가 큰 한 달이었던것 같습니다. 만약 네이버에 지원을 하게 된다면 알려드리겠습니다. 동료 네이버 개발자로서 함께 일하게 된다면 정말 좋겠네요!
신경써주셔서 감사하고, 심사하느라 정말 고생 많으셨습니다!
